
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: blog
        tier: wordpress
    spec:
      containers:
      - image: wordpress:5.2
        name: wordpress
        ports:
        - containerPort: 80
          name: wordpress
        resources:
          limits:
            cpu: 500m
            memory: 768M
          requests:
            cpu: 50m
            memory: 512M
        env:
        - name: WORDPRESS_DB_HOST
          valueFrom:
            secretKeyRef:
              name: blog-db-credentials
              key: WORDPRESS_DB_HOST
        - name: WORDPRESS_DB_NAME
          valueFrom:
            secretKeyRef:
              name: blog-db-credentials
              key: WORDPRESS_DB_NAME
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              name: blog-db-credentials
              key: WORDPRESS_DB_USER
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: blog-db-credentials
              key: WORDPRESS_DB_PASSWORD
        - name: WORDPRESS_CONFIG_EXTRA
          valueFrom:
            secretKeyRef:
              name: blog-config
              key: WORDPRESS_CONFIG_EXTRA
        volumeMounts:
          - name: blog-volume
            mountPath: /var/www/html
      volumes:
        - name: blog-volume
          persistentVolumeClaim:
            claimName: blog-pvc


